"""empty message

Revision ID: 4abcfffe74c0
Revises: 7b4770d9f7b1
Create Date: 2021-08-03 14:19:53.657872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4abcfffe74c0'
down_revision = '7b4770d9f7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bestmovie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bestmovie')
    # ### end Alembic commands ###
