"""empty message

Revision ID: 7b4770d9f7b1
Revises: 23d6b2bba562
Create Date: 2021-08-03 02:39:33.863863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4770d9f7b1'
down_revision = '23d6b2bba562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bestmovie',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('star', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('title')
    )
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'nickname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'pw',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['nickname'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'pw',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'nickname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('bestmovie')
    # ### end Alembic commands ###
