"""empty message

Revision ID: d320b1109345
Revises: bc52dd0f1519
Create Date: 2021-08-02 10:31:19.464902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd320b1109345'
down_revision = 'bc52dd0f1519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_name', sa.String(), nullable=True),
    sa.Column('review_text', sa.String(), nullable=True),
    sa.Column('review_star', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
